# Generated by Django 5.0.5 on 2024-05-16 06:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MainCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
                ('main_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubCategories', to='activity.maincategory')),
            ],
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.PositiveSmallIntegerField()),
                ('end_time', models.PositiveSmallIntegerField()),
                ('date', models.DateField()),
                ('modified_time', models.DateTimeField()),
                ('focus_percentage', models.PositiveSmallIntegerField()),
                ('description', models.TextField()),
                ('main_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.maincategory')),
                ('sub_category_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.subcategory')),
            ],
        ),
    ]
