# Generated by Django 5.0.5 on 2024-05-16 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('activity', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsersActivities', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='main_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.maincategory'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='main_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='SubCategories', to='activity.maincategory'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='UsersSubCategories', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='activity',
            name='sub_category_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activity.subcategory'),
        ),
    ]
